//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketingBrosMP
{


<<<<<<< HEAD
    public partial class CancelReservation
    {

        /// <summary>
        /// pnlNoReservations control.
=======
    public partial class RecentTicketCancellation
    {

        /// <summary>
        /// pnlNoTickets control.
>>>>>>> 1b8cdc045b16b66973df527adcd1cfedf24da153
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Panel pnlNoReservations;

        /// <summary>
        /// rptReservations control.
=======
        protected global::System.Web.UI.WebControls.Panel pnlNoTickets;

        /// <summary>
        /// rptRecentTickets control.
>>>>>>> 1b8cdc045b16b66973df527adcd1cfedf24da153
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Repeater rptReservations;

        /// <summary>
        /// btnCancelReservation control.
=======
        protected global::System.Web.UI.WebControls.Repeater rptRecentTickets;

        /// <summary>
        /// btnCancelTickets control.
>>>>>>> 1b8cdc045b16b66973df527adcd1cfedf24da153
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Button btnCancelReservation;
=======
        protected global::System.Web.UI.WebControls.Button btnCancelTickets;
>>>>>>> 1b8cdc045b16b66973df527adcd1cfedf24da153
    }
}
